apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world-app
  annotations:
    github.com/project-slug: kotak-Gunjan/hello-world-app
spec:
  type: other
  lifecycle: unknown
  owner: guests
